"""Built-in deterministic subsystem modules."""

from cubesat_testbed.modules.base import (
    ModuleCommandError,
    ModuleCommandRequest,
    ModuleError,
    SimulatedModule,
    TelemetrySample,
    normalize_command,
)
from cubesat_testbed.modules.eps import (
    EPS_BATTERY_CELL_DEAD_FAULT,
    EPS_BUS_UNDERVOLTAGE_FAULT,
    EPS_PAYLOAD_RAIL_OFF_COMMAND,
    EPS_PAYLOAD_RAIL_ON_COMMAND,
    EPS_PAYLOAD_RAIL_STUCK_OFF_FAULT,
    EPS_PAYLOAD_RAIL_STUCK_ON_FAULT,
    EPS_POWER_MODE_LOW_POWER_COMMAND,
    EPS_POWER_MODE_NOMINAL_COMMAND,
    EPS_POWER_MODE_SAFE_COMMAND,
    EPS_POWER_OFF_COMMAND,
    EPS_SET_POWER_MODE_COMMAND,
    EPS_SOLAR_ARRAY_OFFLINE_FAULT,
    EpsPowerMode,
    GenericEpsConfig,
    GenericEpsModule,
    GenericEpsState,
)
from cubesat_testbed.modules.payload import (
    PAYLOAD_CAPTURE_ONCE_COMMAND,
    PAYLOAD_CLEAR_DATA_COMMAND,
    PAYLOAD_DOWNLINK_DATA_COMMAND,
    PAYLOAD_POWER_OFF_COMMAND,
    PAYLOAD_POWER_ON_COMMAND,
    PAYLOAD_START_CAPTURE_COMMAND,
    PAYLOAD_STOP_CAPTURE_COMMAND,
    PowerStatus,
    SimplePayloadConfig,
    SimplePayloadModule,
    SimplePayloadState,
)

__all__ = [
    "EPS_BATTERY_CELL_DEAD_FAULT",
    "EPS_BUS_UNDERVOLTAGE_FAULT",
    "EPS_PAYLOAD_RAIL_OFF_COMMAND",
    "EPS_PAYLOAD_RAIL_ON_COMMAND",
    "EPS_PAYLOAD_RAIL_STUCK_OFF_FAULT",
    "EPS_PAYLOAD_RAIL_STUCK_ON_FAULT",
    "EPS_POWER_MODE_LOW_POWER_COMMAND",
    "EPS_POWER_MODE_NOMINAL_COMMAND",
    "EPS_POWER_MODE_SAFE_COMMAND",
    "EPS_POWER_OFF_COMMAND",
    "EPS_SET_POWER_MODE_COMMAND",
    "EPS_SOLAR_ARRAY_OFFLINE_FAULT",
    "PAYLOAD_CAPTURE_ONCE_COMMAND",
    "PAYLOAD_CLEAR_DATA_COMMAND",
    "PAYLOAD_DOWNLINK_DATA_COMMAND",
    "PAYLOAD_POWER_OFF_COMMAND",
    "PAYLOAD_POWER_ON_COMMAND",
    "PAYLOAD_START_CAPTURE_COMMAND",
    "PAYLOAD_STOP_CAPTURE_COMMAND",
    "EpsPowerMode",
    "GenericEpsConfig",
    "GenericEpsModule",
    "GenericEpsState",
    "ModuleCommandError",
    "ModuleCommandRequest",
    "ModuleError",
    "PowerStatus",
    "SimplePayloadConfig",
    "SimplePayloadModule",
    "SimplePayloadState",
    "SimulatedModule",
    "TelemetrySample",
    "normalize_command",
]
